variables:
  ROS_RELEASE: indigo
  REPOSITORY_NAME: mas_datasets

before_script:
  - rm -rf build devel install
  - rm -rf $CI_PROJECT_DIR/../src
  - rm -rf $CI_PROJECT_DIR/../*.tmp
  - source /opt/ros/$ROS_RELEASE/setup.bash

stages:
  - build
  - catkinlint

build:
  stage: build
  script:
    - git pull gitgate@mas.b-it-center.de:mas-group/$REPOSITORY_NAME.git $ROS_RELEASE
    - mkdir -p $CI_PROJECT_DIR/../src
    - cd $CI_PROJECT_DIR/..
    - cp -r $REPOSITORY_NAME src
    - mv src $REPOSITORY_NAME
    - cd $CI_PROJECT_DIR
    - catkin_make
    - source $CI_PROJECT_DIR/devel/setup.bash
    - catkin_make tests
    - catkin_make install
    - catkin_make run_tests
    - catkin_test_results

catkinlint:
  stage: catkinlint
  when: always
  script:
    - catkin_lint --strict .
